// <auto-generated />
using System;
using AgentTaskHarness.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentTaskHarness.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911213813_AddTaskMergeConflictPending")]
    partial class AddTaskMergeConflictPending
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentComponents");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Name")
                        .IsUnique();

                    b.ToTable("AgentDefinitions");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinitionComponent", b =>
                {
                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentDefinitionId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("AgentDefinitionId", "Order")
                        .IsUnique();

                    b.ToTable("AgentDefinitionComponents");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionLink")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("TaskId");

                    b.ToTable("AgentRuns");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConcurrencyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Boards", t =>
                        {
                            t.HasCheckConstraint("CK_Boards_ConcurrencyLimit", "ConcurrencyLimit > 0");
                        });
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Column", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBacklog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentDefinitionId");

                    b.HasIndex("BoardId", "IsBacklog")
                        .IsUnique()
                        .HasFilter("IsBacklog = 1");

                    b.HasIndex("BoardId", "IsTerminal")
                        .IsUnique()
                        .HasFilter("IsTerminal = 1");

                    b.HasIndex("BoardId", "Order")
                        .IsUnique();

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.ColumnTransition", b =>
                {
                    b.Property<Guid>("FromColumnId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToColumnId")
                        .HasColumnType("TEXT");

                    b.HasKey("FromColumnId", "ToColumnId");

                    b.HasIndex("ToColumnId");

                    b.ToTable("ColumnTransitions");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId", "DependsOnTaskId");

                    b.HasIndex("DependsOnTaskId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MergeConflictPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("BoardId", "ColumnId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinition", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Board", "Board")
                        .WithMany("AgentDefinitions")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinitionComponent", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.AgentDefinition", "AgentDefinition")
                        .WithMany("Components")
                        .HasForeignKey("AgentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentTaskHarness.Domain.Entities.AgentComponent", "Component")
                        .WithMany("AgentDefinitions")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentDefinition");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentRun", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Column", "Column")
                        .WithMany("AgentRuns")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentTaskHarness.Domain.Entities.TaskItem", "Task")
                        .WithMany("AgentRuns")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Column", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.AgentDefinition", "AgentDefinition")
                        .WithMany("Columns")
                        .HasForeignKey("AgentDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgentTaskHarness.Domain.Entities.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentDefinition");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.ColumnTransition", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Column", "FromColumn")
                        .WithMany("OutgoingTransitions")
                        .HasForeignKey("FromColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentTaskHarness.Domain.Entities.Column", "ToColumn")
                        .WithMany("IncomingTransitions")
                        .HasForeignKey("ToColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromColumn");

                    b.Navigation("ToColumn");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.TaskDependency", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.TaskItem", "DependsOnTask")
                        .WithMany("DependedOnBy")
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentTaskHarness.Domain.Entities.TaskItem", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Board", "Board")
                        .WithMany("Tasks")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentTaskHarness.Domain.Entities.Column", "Column")
                        .WithMany("Tasks")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Column");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentComponent", b =>
                {
                    b.Navigation("AgentDefinitions");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinition", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Components");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Board", b =>
                {
                    b.Navigation("AgentDefinitions");

                    b.Navigation("Columns");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Column", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("IncomingTransitions");

                    b.Navigation("OutgoingTransitions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("DependedOnBy");

                    b.Navigation("Dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
