// <auto-generated />
using System;
using AgentTaskHarness.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentTaskHarness.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912213525_HierarchicalModelRework")]
    partial class HierarchicalModelRework
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentComponents");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Name")
                        .IsUnique();

                    b.ToTable("AgentDefinitions");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinitionComponent", b =>
                {
                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentDefinitionId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("AgentDefinitionId", "Order")
                        .IsUnique();

                    b.ToTable("AgentDefinitionComponents");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CardType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionLink")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.Property<long>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardType", "CardId");

                    b.ToTable("AgentRuns");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentReviewFailThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConcurrencyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HumanReviewFailThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipFeatureHumanReview")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkipStepHumanReview")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Boards", t =>
                        {
                            t.HasCheckConstraint("CK_Boards_AgentReviewFailThreshold", "AgentReviewFailThreshold >= 0");

                            t.HasCheckConstraint("CK_Boards_ConcurrencyLimit", "ConcurrencyLimit > 0");

                            t.HasCheckConstraint("CK_Boards_HumanReviewFailThreshold", "HumanReviewFailThreshold >= 0");
                        });
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CardType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardType", "CardId", "CreatedAt");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentReviewFailCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysRequireHumanReview")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HumanReviewFailCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MergeConflictPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedSolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowColumn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "WorkflowColumn");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.FeatureDependency", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependsOnFeatureId")
                        .HasColumnType("TEXT");

                    b.HasKey("FeatureId", "DependsOnFeatureId");

                    b.HasIndex("DependsOnFeatureId");

                    b.ToTable("FeatureDependencies");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentReviewFailCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysRequireHumanReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuidanceNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HumanReviewFailCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MergeConflictPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowColumn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId", "WorkflowColumn");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.StepDependency", b =>
                {
                    b.Property<Guid>("StepId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependsOnStepId")
                        .HasColumnType("TEXT");

                    b.HasKey("StepId", "DependsOnStepId");

                    b.HasIndex("DependsOnStepId");

                    b.ToTable("StepDependencies");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinition", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Board", "Board")
                        .WithMany("AgentDefinitions")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinitionComponent", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.AgentDefinition", "AgentDefinition")
                        .WithMany("Components")
                        .HasForeignKey("AgentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentTaskHarness.Domain.Entities.AgentComponent", "Component")
                        .WithMany("AgentDefinitions")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentDefinition");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Feature", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Board", "Board")
                        .WithMany("Features")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.FeatureDependency", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Feature", "DependsOnFeature")
                        .WithMany("DependedOnBy")
                        .HasForeignKey("DependsOnFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentTaskHarness.Domain.Entities.Feature", "Feature")
                        .WithMany("Dependencies")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnFeature");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Step", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Feature", "Feature")
                        .WithMany("Steps")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.StepDependency", b =>
                {
                    b.HasOne("AgentTaskHarness.Domain.Entities.Step", "DependsOnStep")
                        .WithMany("DependedOnBy")
                        .HasForeignKey("DependsOnStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentTaskHarness.Domain.Entities.Step", "Step")
                        .WithMany("Dependencies")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnStep");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentComponent", b =>
                {
                    b.Navigation("AgentDefinitions");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.AgentDefinition", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Board", b =>
                {
                    b.Navigation("AgentDefinitions");

                    b.Navigation("Features");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Feature", b =>
                {
                    b.Navigation("DependedOnBy");

                    b.Navigation("Dependencies");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("AgentTaskHarness.Domain.Entities.Step", b =>
                {
                    b.Navigation("DependedOnBy");

                    b.Navigation("Dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
